# Generated by Django 2.0.6 on 2018-06-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(related_name='_listing_events_+', to='rental.Event')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(related_name='_renter_events_+', to='rental.Event')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='listings',
            field=models.ManyToManyField(related_name='_landlord_listings_+', to='rental.Listing'),
        ),
        migrations.AddField(
            model_name='event',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Landlord'),
        ),
        migrations.AddField(
            model_name='event',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Listing'),
        ),
        migrations.AddField(
            model_name='event',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.Renter'),
        ),
    ]
