# Generated by Django 2.0.6 on 2018-06-24 17:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='listings',
        ),
        migrations.AddField(
            model_name='landlord',
            name='listings',
            field=models.CharField(max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='events',
        ),
        migrations.AddField(
            model_name='listing',
            name='events',
            field=models.CharField(max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.RemoveField(
            model_name='renter',
            name='events',
        ),
        migrations.AddField(
            model_name='renter',
            name='events',
            field=models.CharField(max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
