# Generated by Django 2.0.6 on 2018-06-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20180624_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
