# Generated by Django 2.0.6 on 2018-06-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20180630_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
    ]
