# Generated by Django 2.0.6 on 2018-07-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_auto_20180707_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='renter',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
