# Generated by Django 2.0.6 on 2018-07-12 00:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_auto_20180712_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='events',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
