# Generated by Django 2.0.6 on 2018-07-12 01:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_auto_20180712_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='address',
            field=models.CharField(default='Toronto', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
