# Generated by Django 2.0.6 on 2018-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalUser',
            fields=[
                ('username', models.CharField(choices=[('L', 'Lanlord'), ('R', 'Renter')], max_length=1, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('L', 'Lanlord'), ('R', 'Renter')], max_length=1)),
            ],
        ),
    ]
